server:
  port: 8090

baseUrl: http://localhost:9595/bank/accounts/getAccountDetailsByNumber/8119008115
subbaseUrl: http://localhost:8090/update-service/method2

#spring:
#  application:
#    name: app-2

tracing:
  url: http://jaeger-production-collector.tracing-system.svc.cluster.local:4318/v1/traces
  #url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

